# Generated by Django 4.2.11 on 2024-03-09 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boocks',
            fields=[
                ('id_book', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titler', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=300)),
                ('release_year', models.IntegerField(max_length=4)),
                ('state', models.CharField(max_length=300)),
                ('pages', models.IntegerField()),
                ('publishing_company', models.CharField(max_length=300)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
